### ISSUE TITLE
PlaybackPro Plus clip ID

### ISSUE THREAD

**Issue by matthewcraigtaylor** [bitfocus/companion-module-dtvideolabs-playbackproplus#2]
Companion v1.3.0(d8b8589-1309)

**Describe the bug**
I cannot recall clips in PlaybackPro pro using companion.  Other commands work.  I have sent the commands using packet sender and they execute successfully.  

**To Reproduce**
1. Add PBP module
2. select 'Load clip ID into PVW'
3. Execute
4. Nothing happens

**Screenshots**
![image](https://user-images.githubusercontent.com/34844462/54704289-58b1b500-4b32-11e9-9020-49dd0cab3fb3.png)

**Desktop (please complete the following information):**
 - Win10
 - Chrome
 - Version Companion v1.3.0(d8b8589-1309)

Many thanks

**Comment by matthewcraigtaylor** [comment]
Jeffrey,
I am back in the office now and have a mac running playback pro.
I am using Companion v1.3.0(9ba8221-1382)

I have named clips
001
01
1
11
010
100

All clips are recalling correctly although leading zeros are being ignored.
If I send '001' then '1' is triggered.

I usually use three digits to maintain uniformity.  It also means file browsers keep the correct order.  It works perfectly well ignoring the leading zeros but maybe that could be added in the notes section for the module?

Thank you
Matthew

**Comment by willosof** [comment]
Add ""+ in front of the clip to cast it to a string, jeffrey :)

**Comment by JeffreyDavidsz** [comment]
Thanks for testing! @willosof I'll check that, tnx
